package com.teads.summerschool.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Ensures each bidder's isolated Postgres schema and tables exist before any repository runs.
 *
 * <p>R2DBC has no Hibernate-style ddl-auto, so — unlike the old JPA setup — table creation is
 * explicit here rather than derived from entity annotations. DDL below was captured from the
 * live shared Postgres (bidder_teads schema) to match exactly what years of
 * spring.jpa.hibernate.ddl-auto=update had already produced, not just the current entity source.
 *
 * <p>Runs first among all {@link ApplicationRunner}s ({@link Ordered#HIGHEST_PRECEDENCE}) and
 * blocks once, synchronously, since this is a one-time startup bootstrap step, not part of the
 * reactive request-serving path. {@link com.teads.summerschool.creative.CreativeSeeder} depends
 * on the tables existing and is ordered to run after this.
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SchemaBootstrap implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SchemaBootstrap.class);

    private final DatabaseClient client;
    private final BidderProperties properties;

    public SchemaBootstrap(DatabaseClient client, BidderProperties properties) {
        this.client = client;
        this.properties = properties;
    }

    @Override
    public void run(ApplicationArguments args) {
        String schema = SchemaInitializer.schemaFor(properties.getId());

        Flux.just(
                "CREATE SCHEMA IF NOT EXISTS " + schema,
                """
                CREATE TABLE IF NOT EXISTS %s.bid_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    request_id VARCHAR(255) NOT NULL,
                    floor_price DOUBLE PRECISION NOT NULL,
                    geo VARCHAR(255),
                    device_type VARCHAR(255),
                    audience_segment VARCHAR(255),
                    bid_price DOUBLE PRECISION,
                    creative_id VARCHAR(255),
                    latency_ms INTEGER,
                    no_bid_reason VARCHAR(255),
                    created_at TIMESTAMP(6) NOT NULL,
                    CONSTRAINT uk_bid_record_request_id UNIQUE (request_id)
                )
                """.formatted(schema),
                """
                CREATE TABLE IF NOT EXISTS %s.creatives (
                    id VARCHAR(255) PRIMARY KEY,
                    name VARCHAR(255),
                    description VARCHAR(255),
                    image_url VARCHAR(255),
                    call_to_action VARCHAR(255),
                    bidder_id VARCHAR(255),
                    budget DOUBLE PRECISION NOT NULL,
                    max_bid_price DOUBLE PRECISION,
                    allowed_geos VARCHAR(512),
                    allowed_devices VARCHAR(512),
                    audience_segments VARCHAR(512)
                )
                """.formatted(schema),
                """
                CREATE TABLE IF NOT EXISTS %s.win_notice (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    request_id VARCHAR(255) NOT NULL,
                    bidder_id VARCHAR(255) NOT NULL,
                    clearing_price DOUBLE PRECISION NOT NULL,
                    bid_price DOUBLE PRECISION NOT NULL,
                    received_at TIMESTAMP(6) NOT NULL
                )
                """.formatted(schema)
        )
                .concatMap(sql -> client.sql(sql).fetch().rowsUpdated())
                .then(Mono.fromRunnable(() -> log.info("Ensured database schema+tables exist: {}", schema)))
                .block();
    }
}
